Fix Github Actions (#347)
* workflows: add a workflow_dispatch trigger to start workflows manually

To be able to manually run a workflow from the Github web interface, add
a workflow_dispatch trigger.

Note that this does only work once this change has hit the default
branch.

* workflow: remove python 2.7 testing

Python 2.7 is long obsolete, deprecated and not supported any more.
Remove it from the tests. This test job is especially supposed to run on
ubuntu-20.04, which doesn't have Python 2.7 any more.

Without this patch, this workflow fails with:

  Warning: The support for python 2.7 will be removed on June 19. Related issue: https://github.com/actions/setup-python/issues/672
  Version 2.7 was not found in the local cache
  Error: The version '2.7' with architecture 'x64' was not found for Ubuntu 20.04.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

* setup.py: ignore flake8 warning about module import at top of file

Flake8 is unhappy with us because we violate PEP8:

rsc@leda:~/git/nodeenv$ flake8 --extend-ignore=E127 nodeenv.py tests setup.py
setup.py:16:1: E402 module level import not at top of file

Ignore this warning in this case.

* nodeenv.py: do not compare types

According to this flake8 error:

(env) rsc@leda:~/git/nodeenv$ flake8 --extend-ignore=E127 nodeenv.py tests setup.py
nodeenv.py:421:19: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`

we should not compare types but use isinstance() instead, which can
handle subclasses as well.

See https://www.flake8rules.com/rules/E721.html for details.